name: Build

on: [push]

jobs:
  license-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install REUSE
        run: |
          python -m pip install --upgrade pip
          pip install reuse
      - uses: actions/checkout@v2
      - name: Run REUSE
        run: |
          reuse lint

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest]
        include:
          - python-version: 3.6
            os: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Configure git
      run: |
        git config --global user.email "noreply@cern.ch"
        git config --global user.name "Github actions"
    - name: Test
      run: |
        python -m unittest -v
